// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Role      string    `json:"role"`
	Password  string    `json:"password"`
	Username  string    `json:"username"`
	IsBlocked bool      `json:"is_blocked"`
}
