// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Board struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type Feedback struct {
	ID      int32 `json:"id"`
	UserID  int32 `json:"user_id"`
	BoardID int32 `json:"board_id"`
}

type RefreshToken struct {
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID        int64  `json:"id"`
	Role      string `json:"role"`
	Password  string `json:"password"`
	Username  string `json:"username"`
	IsBlocked bool   `json:"is_blocked"`
}
