// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePublishedOutboxEvents = `-- name: DeletePublishedOutboxEvents :exec
DELETE FROM outbox_events
WHERE published_at IS NOT NULL
  AND created_at < now() - $1::interval
`

func (q *Queries) DeletePublishedOutboxEvents(ctx context.Context, dollar_1 pgtype.Interval) error {
	_, err := q.db.Exec(ctx, deletePublishedOutboxEvents, dollar_1)
	return err
}

const getOutboxEventById = `-- name: GetOutboxEventById :one
SELECT id, aggregate_type, aggregate_id, event_type, payload, created_at, published_at
FROM outbox_events
WHERE id = $1
`

func (q *Queries) GetOutboxEventById(ctx context.Context, id uuid.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventById, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (
  aggregate_type,
  aggregate_id,
  event_type,
  payload
) VALUES (
  $1, $2, $3, $4
) RETURNING id, aggregate_type, aggregate_id, event_type, payload, created_at, published_at
`

type InsertOutboxEventParams struct {
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, created_at, published_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
