// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, username, expires_at) VALUES ($1, $2, $3) RETURNING token, username, expires_at
`

type CreateRefreshTokenParams struct {
	Token     string    `json:"token"`
	Username  string    `json:"username"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.Token, arg.Username, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(&i.Token, &i.Username, &i.ExpiresAt)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens WHERE token = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, token)
	return err
}

const deleteRefreshTokensByUsername = `-- name: DeleteRefreshTokensByUsername :exec
DELETE FROM refresh_tokens WHERE username = $1
`

func (q *Queries) DeleteRefreshTokensByUsername(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUsername, username)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token, username, expires_at FROM refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(&i.Token, &i.Username, &i.ExpiresAt)
	return i, err
}
