// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "Users" (
  password,
  username
) VALUES (
  $1, $2
) RETURNING id, role, password, username, is_blocked
`

type CreateUserParams struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Password, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Password,
		&i.Username,
		&i.IsBlocked,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, role, password, username, is_blocked FROM "Users" 
WHERE ID = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Password,
		&i.Username,
		&i.IsBlocked,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, password, username, is_blocked FROM "Users" 
WHERE Username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Password,
		&i.Username,
		&i.IsBlocked,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, role, password, username, is_blocked FROM "Users"
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Password,
			&i.Username,
			&i.IsBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE "Users"
SET username = $2
WHERE id = $1
RETURNING id, role, password, username, is_blocked
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Password,
		&i.Username,
		&i.IsBlocked,
	)
	return i, err
}
