CREATE TABLE "Users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar NOT NULL DEFAULT 'USER',
  "password" varchar NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "is_blocked" bool NOT NULL DEFAULT false 
);

CREATE TABLE "Boards" (
  "id" integer PRIMARY KEY,
  "user_id" integer NOT NULL
);

CREATE TABLE "Feedbacks" (
  "id" integer PRIMARY KEY,
  "user_id" integer NOT NULL,
  "board_id" integer NOT NULL
);

ALTER TABLE "Boards" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Feedbacks" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Feedbacks" ADD FOREIGN KEY ("board_id") REFERENCES "Boards" ("id") DEFERRABLE INITIALLY IMMEDIATE;
