syntax = "proto3";

package pb;

option go_package = "github.com/koliader/tellmi-users";

import "Entity.proto";

service Users {
  rpc Register(RegisterReq) returns (AuthRes) {}
  rpc Login(LoginReq) returns (AuthRes) {}
  rpc GetUserById(IdReq) returns (UserRes) {}
  rpc ListUsers(Empty) returns (ListUserRes) {}
}

message RegisterReq {
  string username = 1;
  string password = 2;
}

message LoginReq {
  string username = 1;
  string password = 2;
}

message AuthRes {
  string token = 1;
}

message IdReq {
  int64 id = 1;
}

message UserRes {
  User user = 1;
}

message ListUserRes {
  repeated User users = 1;
}
